### ISSUE TITLE
fusecompress does not compile with boost library v1.41

### ISSUE THREAD

**Issue by ghost** [tex/fusecompress#3]
Code needs some minor fix, I get these errors:

In file included from Compress.cpp:39:
./boost/iostreams/device/nonclosable_file_descriptor.hpp: In constructor ‘boost::iostreams::nonclosable_file_descriptor::nonclosable_file_descriptor(const std::string&, std::_Ios_Openmode, std::_Ios_Openmode)’:
./boost/iostreams/device/nonclosable_file_descriptor.hpp:34: error: no matching function for call to ‘boost::iostreams::file_descriptor::file_descriptor(const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::_Ios_Openmode&, std::_Ios_Openmode&)’
/usr/include/boost/iostreams/device/file_descriptor.hpp:81: note: candidates are: boost::iostreams::file_descriptor::file_descriptor(const boost::iostreams::file_descriptor&)
/usr/include/boost/iostreams/device/file_descriptor.hpp:66: note:                 boost::iostreams::file_descriptor::file_descriptor(const char*, std::_Ios_Openmode)
/usr/include/boost/iostreams/device/file_descriptor.hpp:61: note:                 boost::iostreams::file_descriptor::file_descriptor(const std::string&, std::_Ios_Openmode)
/usr/include/boost/iostreams/device/file_descriptor.hpp:55: note:                 boost::iostreams::file_descriptor::file_descriptor(boost::iostreams::detail::file_handle, bool)
/usr/include/boost/iostreams/device/file_descriptor.hpp:52: note:                 boost::iostreams::file_descriptor::file_descriptor()
